name = "SubmodularUtilities"
uuid = "bb4d9fe8-f697-11e8-2652-9d5135554a07"
authors = ["Lin Chen <abratdarcy@gmail.com>"]
version = "0.0.3"

[deps]
Clp = "e2554f3b-3117-50c0-817c-e040a3ddf72d"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
